version: "2"

services:
  web:
    build: .
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: postgres://admin:admin@postgres_1:5432/rrep
    volumes:
      - ./src:/app/src
    networks:
      - front
      - back
  postgres:
    image: postgres:9.5.0
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    networks:
      - back
    volumes:
      - postgres-data:/etc/postgresql
      - postgres-data:/var/log/postgresql
      - postgres-data:/var/lib/postgresql

volumes:
  postgres-data:
    driver: local

networks:
  front:
    driver: bridge
  back:
    driver: bridge
